apiVersion: apps/v1
kind: Deployment

metadata:
  name: tasker-api
  namespace: tasker

spec:
  replicas: 1

  selector:
    matchLabels:
      app: tasker-api

  template:
    metadata:
      labels:
        app: tasker-api

    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: tasker-api
          image: ghcr.io/chuuch/tasker:latest

          ports:
            - containerPort: 8080

          env:
            - name: DATABASE_HOST
              value: postgres

            - name: DATABASE_PORT
              value: "5432"

            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: tasker-db-secret
                  key: POSTGRES_USER

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tasker-db-secret
                  key: POSTGRES_PASSWORD

            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: tasker-db-secret
                  key: POSTGRES_DB

            - name: DATABASE_SSLMODE
              value: disable

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
