apiVersion: batch/v1
kind: Job

metadata:
  name: tasker-migration
  namespace: tasker

spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: OnFailure

      containers:
        - name: migrate
          image: migrate/migrate:v4.19.1

          command:
            - migrate

          args:
            - -path=/migrations
            - -database=postgres://tasker:tasker_password@postgres:5432/tasker_db?sslmode=disable
            - up

          volumeMounts:
            - name: migrations
              mountPath: /migrations

      volumes:
        - name: migrations
          configMap:
            name: tasker-migration
