apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "tasker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "tasker.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "tasker.selectorLabels" . | nindent 8 }}

    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}

      containers:
        - name: tasker-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          envFrom:
            - configMapRef:
                name: {{ include "tasker.fullname" . }}-config

          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secret.name }}
                  key: POSTGRES_USER

            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secret.name }}
                  key: POSTGRES_PASSWORD

            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secret.name }}
                  key: POSTGRES_DB

          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.api.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.livenessProbe.periodSeconds }}

          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: {{ .Values.api.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.readinessProbe.periodSeconds }}
