apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.database.secret.name }}
  namespace: {{ .Release.Namespace }}

type: Opaque

stringData:
  POSTGRES_USER: tasker
  POSTGRES_PASSWORD: tasker_password
  POSTGRES_DB: tasker_db
