apiVersion: v1
kind: Service

metadata:
  name: {{ include "tasker.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}

spec:
  type: ClusterIP

  selector:
    app: {{ include "tasker.fullname" . }}-postgres

  ports:
    - name: postgres
      port: {{ .Values.database.service.port }}
      targetPort: postgres
      protocol: TCP
