name: CI

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: tasker
          POSTGRES_PASSWORD: tasker_password
          POSTGRES_DB: tasker_db_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U tasker -d tasker_db_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.19.1/migrate.linux-amd64.tar.gz \
            | tar -xz
          sudo mv migrate /usr/local/bin/migrate

      - name: Run database migrations
        run: migrate -path migrations -database "postgres://tasker:tasker_password@localhost:5432/tasker_db_test?sslmode=disable" up

      - name: Run tests
        run: go test ./...

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/tasker:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/tasker:latest
